import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="min-h-full flex flex-col text-sm">
      <Head>
        <title>Oklama Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/file.png" />
      </Head>

      <main className="absolute inset-0 overflow-hidden select-none z-10">
        <div className="absolute top-0 left-0 bottom-[90px] right-[90px]  border-red-500">
          {/* file container */}
          <div className="absolute bottom-[50vh] left-[50vw] text-sm flex flex-col items-center justify-center pointer-events-none w-[90px] hover:border-2 hover:border-dotted border-black">
            <Image
              src={"/file.png"}
              width={64}
              height={64}
              className=" pointer-events-auto"
              style={{ imageRendering: "pixelated" }}
            />
            <span className="pointer-events-auto text-[13px] text-center bg-white">
              nu thoughts
            </span>
          </div>
        </div>
      </main>

      {/* top nav options */}
      <div className="fixed top-8 left-8 z-30 text-black/50 font-mono text-[13px] cursor-pointer">
        <span className="hover:text-[#cd3f25]">music</span>
      </div>

      <div className="fixed top-8 right-8 z-30 text-black/50 font-mono text-[13px] cursor-pointer">
        <span className="hover:text-[#cd3f25]">tour</span>
      </div>

      {/* footer */}
      <div className="fixed bottom-8 left-0 right-0 h-0 flex justify-center items-center z-30">
        <div className="absolute bottom-0 text-black/50 font-mono">
          <a
            className="hover:text-[#cd3f25]"
            href="https://twitter.com/kendricklamar"
            target="_blank"
            rel="noreferrer"
          >
            twitter
          </a>{" "}
          /{" "}
          <a
            className="hover:text-[#cd3f25]"
            href="https://www.instagram.com/kendricklamar/"
            target="_blank"
            rel="noreferrer"
          >
            instagram
          </a>{" "}
          /{" "}
          <a
            className="hover:text-[#cd3f25]"
            href="https://www.facebook.com/kendricklamar"
            target="_blank"
            rel="noreferrer"
          >
            facebook
          </a>{" "}
          /{" "}
          <a
            className="hover:text-[#cd3f25]"
            href="https://www.youtube.com/channel/UC3lBXcrKFnFAFkfVk5WuKcQ/videos"
            target="_blank"
            rel="noreferrer"
          >
            youtube
          </a>
        </div>
      </div>
    </div>
  );
};

export default Home;
